---
#############################
#    Experiment Settings    #
#############################

# Max ticks for simulation
ticks: 1

files:
  out_dir: "./outputs/"
  agents_dir: "./data/civ_withCar_bldg_np.csv"
  buildings_dir: "./data/bldg_with_inst_orig.csv"
  infection_dir: "./data/infection_prob.csv"
  admission_dir: "./data/admission_prob.csv"
  mortality_dir: "./data/mortality_prob.csv"

profile: False
debug: True

# Columns to read
cols:
  agent: [0, 11, 2, 6]
  house: [1]
  employ: [3, 12, 10]
  building: [6, 2, 3, 12, 4, 2, 14, 15, 17, 18]

# Data size
# Put null for full data size
rows:
  agent: 1000
  house: 1000
  employ: 1000
  building: 1200

# USG for Jerusalem
usg:
  school0: [5305]
  school1: [5310]
  school2: [5338]
  schoolR0: [5300]
  schoolR1: [5312]
  schoolR2: [5523, 5525]
  schoolR3: [5340]
  etc: [6512, 6520, 6530, 6600, 5740, 5760, 5600, 5700, 5202, 5253]
  religious: [5501, 5521]

#############################
#       Hyperparameter      #
#############################

# Type of buildings to lockdown
theme:
  EDU: False
  REL: False
  ALL: True

# Lockdown mode
scenario:
  DIFF: False
  GRADUAL: False

# official disease-related parameters
disease:
  recover: [21, 28]
  diagnose: 7

# Distance threshold to define closeness of two nodes
distance:
  dist_ab: 1
  dist_bb: 6

# Set the weights for torch.multinomial operation of get_routine function in model.py
# It randomly chooses a building from all available building
# Possible buildings for non-regular activities vs impossible buildings
# If a possible building is chosen for an agent, it means the agent has one non-regular activity
multinomial:
  symmetry: True
  # Only evaluates if symmetry: False
  asymmetry:
    possible: 6.0
    impossible: 4.0

BB:
  threshold: 0.00161
  beta: 2

AA:
  threshold: 0.95
  # weights for agent-agent network components (income, age, buildings)
  weights:
    income: 1
    age: 1
    dist: 1

density:
  job: [0, 0.0004733, 0, 0.0315060, 0.0479474]

income:
  avg: 7177.493
  std: 1624.297
